import { Generator, Parity } from "./generator.js";
import * as Lib from "./littleLib.js";

// new Generator()
// 	// .setSeed(6605771)
// 	.setSize(200, 200)
// 	.setRoomMinSize(20)
// 	.setRoomMinSizeK(1)
// 	// .setSquareChance(0.5)
// 	.setGap(4)
// 	.setRoomRoadGap(2)
// 	.setDivideK(0, 1)
// 	.setRoadWidth(2, 4)
// 	// .setRoadAlwaysFromRoomCenter(true)
// 	// .setImproveConnectionsEnabled(false)
// 	.setMinImprovePercentOnConnectionsAdd(5)
// 	.setDisplay(true)
// 	.gen();

new Generator()
	.setSeed(7635299)
	// .setSeed(6200421)
	// .setSeed(2456052)
	.setSize(300, 300)
	.setMultiplicity(4)
	// .setParity(Parity.even, Parity.even)
	.setRoomMinSize(20)
	.setRoomMinSizeK(1)
	// .setSquareChance(0.5)
	.setGap(12)
	.setRoomRoadGap(4)
	.setDivideK(0, 1)
	.setRoadWidth(6, 15)
	// .setRoadWidth(4, 4)
	// .setRoadWidth(4, 400)
	// .setRoadAlwaysFromRoomCenter(true)
	// .setImproveConnectionsEnabled(false)
	.setMinImprovePercentOnConnectionsAdd(5)
	.setDisplay(true)
	.gen();

